version: "3.7"

services:
  mysqlcurso:
    build:
      context: .
      dockerfile: Dockerfile
#    image: mysql:5.7
    container_name: mysqlcurso
    restart: always
    ports:
      - "3806:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


